<?php
/**
 * CouponType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DillerAPI
 * @author   DILLER AS
 * @link     https://diller.io
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DillerAPI\Model;
use \DillerAPI\ObjectSerializer;

/**
 * CouponType Class Doc Comment
 *
 * @category Class
 * @package  DillerAPI
 * @author   DILLER AS
 * @link     https://diller.io
 */
class CouponType
{
    /**
     * Possible values of this enum
     */
    const STANDARD = 'Standard';
    const WELCOME = 'Welcome';
    const CAMPAIGN = 'Campaign';
    const _PUBLIC = 'Public';
    const RECURRING = 'Recurring';
    const BIRTHDAY = 'Birthday';
    const CHILD_BIRTHDAY = 'ChildBirthday';
    const AUTOMATION = 'Automation';
}
