<?php
/**
 * Gender
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DillerAPI
 * @author   DILLER AS
 * @link     https://diller.io
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DillerAPI\Model;
use \DillerAPI\ObjectSerializer;

/**
 * Gender Class Doc Comment
 *
 * @category Class
 * @package  DillerAPI
 * @author   DILLER AS
 * @link     https://diller.io
 */
class Gender
{
    /**
     * Possible values for this enum
     */
    public const NUMBER_MALE = 'Male';
    public const NUMBER_FEMALE = 'Female';
    public const NUMBER_NOT_SHARED = 'NotShared';
    public const NUMBER_NON_BINARY = 'NonBinary';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NUMBER_MALE
            self::NUMBER_FEMALE
            self::NUMBER_NOT_SHARED
            self::NUMBER_NON_BINARY
        ];
    }
}
